"""add_free_quantity_and_discount_percent_to_purchase_items

Revision ID: 655d2a756cd6
Revises: 527ef11c9a3e
Create Date: 2026-07-10 16:24:33.664836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655d2a756cd6'
down_revision: Union[str, Sequence[str], None] = '527ef11c9a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_items', sa.Column('free_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('purchase_items', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'discount_percent')
    op.drop_column('purchase_items', 'free_quantity')
    # ### end Alembic commands ###
